services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: holywater
    ports:
      - "5432:5432"
    volumes:
      - holywater_pg:/var/lib/postgresql/data

volumes:
  holywater_pg:
